export const talentDNAData = [
  {
    candidateId: "1",
    name: "Sarah Chen",
    avatar: "SC",
    role: "Senior Frontend Engineer",
    predictedSuccess: 92,
    overallScore: 88,
    dimensions: [
      { trait: "Technical", score: 95 },
      { trait: "Problem Solving", score: 90 },
      { trait: "Communication", score: 82 },
      { trait: "Leadership", score: 75 },
      { trait: "Adaptability", score: 88 },
      { trait: "Creativity", score: 85 },
    ],
    personality: {
      confidence: 87,
      clarity: 91,
      emotionalIntelligence: 78,
      leadershipBehavior: 72,
      teamOrientation: 85,
    },
    recommendation: "Strong Hire",
    insights: [
      "Exceptional technical depth with system design expertise",
      "Strong communicator, excels in cross-functional settings",
      "Growth potential in leadership roles within 12 months",
    ],
  },
  {
    candidateId: "2",
    name: "Marcus Johnson",
    avatar: "MJ",
    role: "Product Manager",
    predictedSuccess: 85,
    overallScore: 83,
    dimensions: [
      { trait: "Technical", score: 70 },
      { trait: "Problem Solving", score: 88 },
      { trait: "Communication", score: 94 },
      { trait: "Leadership", score: 90 },
      { trait: "Adaptability", score: 82 },
      { trait: "Creativity", score: 86 },
    ],
    personality: {
      confidence: 92,
      clarity: 88,
      emotionalIntelligence: 90,
      leadershipBehavior: 91,
      teamOrientation: 93,
    },
    recommendation: "Hire",
    insights: [
      "Natural leader with strong stakeholder management",
      "Excellent strategic thinking and prioritization skills",
      "Lower technical depth — may need engineering support",
    ],
  },
  {
    candidateId: "5",
    name: "Elena Rodriguez",
    avatar: "ER",
    role: "UX Designer",
    predictedSuccess: 79,
    overallScore: 81,
    dimensions: [
      { trait: "Technical", score: 78 },
      { trait: "Problem Solving", score: 82 },
      { trait: "Communication", score: 88 },
      { trait: "Leadership", score: 65 },
      { trait: "Adaptability", score: 90 },
      { trait: "Creativity", score: 96 },
    ],
    personality: {
      confidence: 74,
      clarity: 86,
      emotionalIntelligence: 88,
      leadershipBehavior: 60,
      teamOrientation: 91,
    },
    recommendation: "Hire",
    insights: [
      "Outstanding creative and visual thinking ability",
      "High empathy — ideal for user-centered design roles",
      "Would benefit from mentorship in leadership contexts",
    ],
  },
  {
    candidateId: "4",
    name: "James Wilson",
    avatar: "JW",
    role: "Backend Engineer",
    predictedSuccess: 94,
    overallScore: 91,
    dimensions: [
      { trait: "Technical", score: 97 },
      { trait: "Problem Solving", score: 93 },
      { trait: "Communication", score: 76 },
      { trait: "Leadership", score: 80 },
      { trait: "Adaptability", score: 84 },
      { trait: "Creativity", score: 72 },
    ],
    personality: {
      confidence: 82,
      clarity: 79,
      emotionalIntelligence: 70,
      leadershipBehavior: 78,
      teamOrientation: 75,
    },
    recommendation: "Strong Hire",
    insights: [
      "Top-tier technical candidate — deep systems knowledge",
      "Could improve on soft-skill communication",
      "High predicted retention based on role-fit analysis",
    ],
  },
];

export const skillVerificationResults = [
  { skill: "React", claimed: true, verified: true, score: 95 },
  { skill: "TypeScript", claimed: true, verified: true, score: 88 },
  { skill: "System Design", claimed: true, verified: true, score: 82 },
  { skill: "GraphQL", claimed: true, verified: false, score: 45 },
  { skill: "Node.js", claimed: true, verified: true, score: 76 },
];
